profile:
  name: "online"

mysql:
  host: "10.0.6.215"
  port: 3306
  username: "aliadb"
  password: "AliAdb1q!zaqxsw"
  database: "online_crm_db"
  tables:
    - "online_crm_db.crm_student"
    - "online_crm_db.crm_clue_extend"
    - "online_crm_db.crm_follow"
    - "online_crm_db.crm_qw_retailcode_user"
    - "online_crm_db.crm_qw_friend_info"
    - "online_crm_db.crm_qw_friend_mobiles"
    - "online_crm_db.crm_order"
    - "online_crm_db.serve_record"
    - "online_crm_db.crm_service_details"
    - "online_crm_db.crm_qw_groupchat"
    - "online_crm_db.crm_qw_groupchat_tag"
    - "online_crm_db.crm_admin"
  server-id-range: "5700-5720"

kafka:
  bootstrap:
    servers: "alikafka-pre-cn-cq74s3ce2001-1-vpc.alikafka.aliyuncs.com:9092,alikafka-pre-cn-cq74s3ce2001-2-vpc.alikafka.aliyuncs.com:9092,alikafka-pre-cn-cq74s3ce2001-3-vpc.alikafka.aliyuncs.com:9092"
  topic: "crm-cdc-events-topic-online"
  transaction:
    timeout-ms: 900000

flink:
  parallelism: 1
  checkpoint:
    interval-ms: 60000
    timeout-ms: 600000
    min-pause-ms: 30000
    max-concurrent: 1
  restart:
    attempts: 10
    delay-seconds: 10
