profile:
  name: "dev"

mysql:
  host: "10.0.6.111"
  port: 3306
  username: "aliadb"
  password: "V8%jbQtsR&*W"
  database: "dev_crm_db_new"
  tables:
    - "dev_crm_db_new.crm_student"
    - "dev_crm_db_new.crm_clue_extend"
    - "dev_crm_db_new.crm_follow"
    - "dev_crm_db_new.crm_qw_retailcode_user"
    - "dev_crm_db_new.crm_qw_friend_info"
    - "dev_crm_db_new.crm_qw_friend_mobiles"
    - "dev_crm_db_new.crm_order"
    - "dev_crm_db_new.serve_record"
    - "dev_crm_db_new.crm_service_details"
    - "dev_crm_db_new.crm_qw_groupchat"
    - "dev_crm_db_new.crm_qw_groupchat_tag"
    - "dev_crm_db_new.crm_admin"
  server-id-range: "5400-5420"

kafka:
  bootstrap:
    servers: "alikafka-post-cn-n1e4ounyr002-1-vpc.alikafka.aliyuncs.com:9092,alikafka-post-cn-n1e4ounyr002-2-vpc.alikafka.aliyuncs.com:9092,alikafka-post-cn-n1e4ounyr002-3-vpc.alikafka.aliyuncs.com:9092"
  topic: "crm-cdc-events-topic-dev"
  transaction:
    timeout-ms: 900000

flink:
  parallelism: 1
  checkpoint:
    interval-ms: 60000
    timeout-ms: 600000
    min-pause-ms: 30000
    max-concurrent: 1
  restart:
    attempts: 10
    delay-seconds: 10
